### ISSUE TITLE
Regarding 'wget' in MAC

### ISSUE THREAD

**Issue by mdabir1203** [ayoub0x1/born2beroot#1]
Normally wget doesn't work unless you installed it. So a good alternative would be to use **curl** *sites to download*

**Comment by ayoub0x1** [comment]
Hello, thank you for reporting it,
usually, this project is about virtualization, it has to be done on a virtual machine, either Debian or Centos not on your MAC, so, you can follow the steps that I provided to you to install wget.
thank you
